# Generated by Django 2.0.3 on 2019-04-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumulative_goal',
            name='chunk_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cumulative_goal',
            name='period',
            field=models.IntegerField(default=0),
        ),
    ]
