# Generated by Django 2.0.3 on 2019-04-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_goal_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal_progress',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
