# Generated by Django 2.0.3 on 2019-04-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_auto_20190424_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='target_date',
            field=models.DateField(default='2019-04-22'),
        ),
    ]
