# Generated by Django 2.0.3 on 2019-05-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_cumulative_goal_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone_goal',
            name='final_goal',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='milestone_goal',
            name='step_eight',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='milestone_goal',
            name='step_eight_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milestone_goal',
            name='step_five',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='milestone_goal',
            name='step_five_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milestone_goal',
            name='step_four',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='milestone_goal',
            name='step_four_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milestone_goal',
            name='step_nine',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='milestone_goal',
            name='step_nine_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milestone_goal',
            name='step_one',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='milestone_goal',
            name='step_one_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milestone_goal',
            name='step_seven',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='milestone_goal',
            name='step_seven_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milestone_goal',
            name='step_six',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='milestone_goal',
            name='step_six_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milestone_goal',
            name='step_ten',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='milestone_goal',
            name='step_ten_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milestone_goal',
            name='step_three',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='milestone_goal',
            name='step_three_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milestone_goal',
            name='step_two',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='milestone_goal',
            name='step_two_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='milestone_goal',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
