# Generated by Django 2.0.3 on 2019-05-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_auto_20190504_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone_goal',
            name='goal_ptr',
        ),
        migrations.DeleteModel(
            name='Milestone_Goal',
        ),
    ]
