# Generated by Django 2.0.3 on 2019-05-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_auto_20190512_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal_progress',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
